project:
  type: website

website:
  title: "Citi Bikes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - hourlydemand.qmd
      - monthlydemand.qmd
      - membervcasual.qmd
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



