---
title: "Hourly Demand"
author: "Angelo Morelli"
format: html
execute:
  echo: false
  message: false
  warning: false
---

```{r}
#| label: setup

library(tidyverse)
library(ggplot2)
library(scales)
library(readr)
```

```{r}
#| cache: TRUE

june_data <- read_csv(unzip("202406-citibike-tripdata.zip"))

december_data <- read_csv(unzip("202412-citibike-tripdata.zip"))
                          
trip_data <- bind_rows(june_data, december_data)
```


```{r}
# Example: Aggregate trips by hour of the day
hourly_demand <- trip_data |>
  mutate(hour = as.numeric(format(started_at, "%H"))) |>
  group_by(hour) |>
  summarise(total_trips = n())

# Plot hourly demand
ggplot(hourly_demand, aes(x = hour, 
                          y = total_trips)) +
  geom_line(group = 1, 
            color = "darkblue") +
  labs(title = "Bike Demand by Hour of the Day",
       x = "Hour of the Day",
       y = "Total Trips") +
  scale_x_continuous(breaks = 0:23, 
                     labels = paste0(0:23, ":00")) +
  scale_y_continuous(breaks = seq(0, 
                                  max(hourly_demand$total_trips), 
                                  by = 100000), 
                     labels = unit_format(unit = "k", 
                                          scale = 1e-3)) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, 
                                   hjust = 1))
```
